version: 2

before:
  hooks:
    - go mod tidy

# Disable release creation for now
release:
  disable: true

builds:
  - env: ["CGO_ENABLED=0"]
    binary: jfrog-credential-provider
    goos:
      # - darwin
      - linux
    goarch:
      - amd64
      - arm64

## Ko-build doesn't work since the path of the binary is always /ko-app/jfrog-credential-provider for all 
## architectures and the download script of the helm chart will append the suffix "-<ARCH_SUFFIX>" on the download url.
## See /helm/templates/configmap-setup.yaml for more details.
# kos:
#   - base_image: releases-docker.jfrog.io/jfrog/alpine-with-tools:3.21.0
#     repositories:
#       - to-be-defined.example.com/jfrog-credential-provider
#     tags:
#       - "{{.Version}}"
#       # - latest

#     # Bare uses a tag on the $KO_DOCKER_REPO without anything additional.
#     bare: true
#     # preserve_import_paths: false
#     platforms:
#       - linux/amd64
#       - linux/arm64
#     sbom: none

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - to-be-defined.example.com/jfrog-credential-provider
    tags:
      - "{{ .Version }}-SNAPSHOT"
      # - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: jfrog-credentials-provider
      org.opencontainers.image.source: https://github.com/jfrog/jfrog-credentials-provider
      org.opencontainers.image.version: v{{ .Version }}
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: Apache-2.0
