resources:
  - name: kubelet_credentials_provider_github
    type: GitRepo
    configuration:
      gitProvider: credentials_provider_github
      path: jfrog/jfrog-credentials-provider
      branches:
        include: feature/pipelines
      buildOn:
        releaseCreate: true

pipelines:
  - name: jfrog_credentials_provider_release
    configuration:
      integrations:
        - name: entplus_deployer
        - name: entplus_jfrog_io_docker
        - name: credentials_provider_github  # Add GitHub integration for API access
    steps:
      - name: push_release_artifacts_to_entplus
        type: Bash
        configuration:
          environmentVariables:
            USE_LOCAL_JFROG_CLI: 'true'
            # Add GitHub token for API access
            GITHUB_TOKEN: $int_credentials_provider_github_token
            GITHUB_RELEASE_TAG_NAME:
              default: ${res_kubelet_credentials_provider_github_gitTagName}
              values:
                - ""
              description: "Allow custom tag name for the release"
              allowCustom: true
            GITHUB_REPO_URL: "https://github.com/jfrog/jfrog-credentials-provider"
          inputResources:
            - name: kubelet_credentials_provider_github
              trigger: true
        execution:
          onStart:
            - task: jfrog/setup-jfrog-cli@v0.2.0
              input:
                version: "2.72.2"
            - jf --version | echo "True"
            - jfrog --version
            - echo "Based out of release ${res_kubelet_credentials_provider_github_isRelease}"
            - echo "Installing Github CLI"
            - |
              ARCH=$(uname -m)
              ARCH_SUFFIX="amd64"
              if [ "$ARCH" = "x86_64" ]; then
                  ARCH_SUFFIX="amd64"
              elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
                  ARCH_SUFFIX="arm64"
              fi
            - curl -L "https://github.com/cli/cli/releases/download/v2.74.2/gh_2.74.2_linux_$ARCH_SUFFIX.tar.gz" | tar xz
            - sudo mv "gh_2.74.2_linux_$ARCH_SUFFIX"/bin/gh /usr/local/bin/gh
            - sudo chmod +x /usr/local/bin/gh
            - echo "Github CLI installed"
            - /usr/local/bin/gh version
          onExecute:
            - echo "Pushing tag ${GITHUB_RELEASE_TAG_NAME} with release ${res_kubelet_credentials_provider_github_releaseName}"
            - mkdir -p "release-${GITHUB_RELEASE_TAG_NAME}" && cd "release-${GITHUB_RELEASE_TAG_NAME}"
            - /usr/local/bin/gh release download "${GITHUB_RELEASE_TAG_NAME}" --repo "${GITHUB_REPO_URL}" --clobber
            - echo "Strip V if it exists"
            - ENTPLUS_REPOSITORY_VERSION=$(echo "${GITHUB_RELEASE_TAG_NAME}" | sed 's/^v//')
            - jfrog rt u "*" --url "${int_entplus_deployer_url}" --user "${int_entplus_deployer_user}" --password "${int_entplus_deployer_apikey}" "inst-jfrog-kubelet-credentials-provider/${ENTPLUS_REPOSITORY_VERSION}/"
            - echo "Finished pushing artifacts to entplus"
