resources:
  - name: kubelet_credentials_provider_github
    type: GitRepo
    configuration:
      gitProvider: credentials_provider_github
      path: jfrog/jfrog-credentials-provider
      branches:
        include: feature/pipelines
      buildOn:
        releaseCreate: true

pipelines:
  - name: jfrog_credentials_provider_release
    configuration:
      integrations:
        - name: entplus_deployer
        - name: entplus_jfrog_io_docker
        - name: credentials_provider_github  # Add GitHub integration for API access
    steps:
      - name: push_release_artifacts_to_entplus
        type: Bash
        configuration:
          environmentVariables:
            USE_LOCAL_JFROG_CLI: 'true'
            # Add GitHub token for API access
            GITHUB_TOKEN: $int_credentials_provider_github_token
          inputResources:
            - name: kubelet_credentials_provider_github
              trigger: true
        execution:
          onStart:
            - echo "Based out of release ${res_kubelet_credentials_provider_github_isRelease}"
            - echo "Downloading the release artifacts from GitHub"
            - brew install gh
            - gh version
            - echo "Tag name being ${res_kubelet_credentials_provider_github_gitTagName}"
            - echo "name ${res_kubelet_credentials_provider_github_releaseName}"
            - echo "Description ${res_kubelet_credentials_provider_github_releaseDescription}"
            - echo "Tag ${res_kubelet_credentials_provider_github_releaseTag}"
            - echo "Assets ${res_kubelet_credentials_provider_github_releaseAssets}"
